Loading the Trained models

In [3]:
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd
import tensorflow as tf
import pickle

In [4]:
model = load_model("models/model.h5")

In [ ]:
label_encoder_gender_path = "models/label_encoder_gender.pkl"
one_hot_encoder_geography_path = "models/one_hot_encoder_geography.pkl"
standard_scaler_path = "models/std_scaler.pkl"
with open(label_encoder_gender_path,"rb") as file:
    label_encoder_gender = pickle.load(file)

with open(one_hot_encoder_geography_path,"rb") as file:
    one_hot_encoder_geography = pickle.load(file)

with open(standard_scaler_path,"rb") as file:
    scaler = pickle.load(file)


In [72]:
input_data = {
    "CreditScore":600,
    "Geography":"France",
    "Gender":"Male",
    "Age":40,
    "Tenure":3,
    "Balance":60000,
    "NumOfProducts":2,
    "HasCrCard":1,
    "IsActiveMember":1,
    "EstimatedSalary":50000

}

In [ ]:
df = pd.DataFrame([input_data])

CreditScore Geography Gender  ...  HasCrcard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [ ]:
gender_encoded = label_encoder_gender.transform([input_data["Gender"]])


In [32]:
input_data

{'CreditScore': 600,
 'Geography': 'France',
 'Gender': 'Male',
 'Age': 40,
 'Tenure': 3,
 'Balance': 60000,
 'NumOfProducts': 2,
 'HasCrcard': 1,
 'IsActiveMember': 1,
 'EstimatedSalary': 50000}

In [23]:
input_data["Geography"]

'France'

In [26]:
geo_encoded = one_hot_encoder_geography.transform([[input_data["Geography"]]]).toarray()

c:\Users\HP\OneDrive\Documents\CustomerChurnPrediction\churnpred\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [27]:
geo_encoded

array([[1., 0., 0.]])

In [29]:
geo_encoded = one_hot_encoder_geography.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=one_hot_encoder_geography.get_feature_names_out(["Geography"]))

c:\Users\HP\OneDrive\Documents\CustomerChurnPrediction\churnpred\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [40]:
geo_encoded

array([[1., 0., 0.]])

In [ ]:
df = pd.DataFrame([input_data])

In [73]:
df = pd.DataFrame([input_data])
gender_encoded = label_encoder_gender.transform([input_data["Gender"]])
df["Gender"]=pd.DataFrame(gender_encoded,columns=["Gender"])

geo_encoded = one_hot_encoder_geography.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=one_hot_encoder_geography.get_feature_names_out(["Geography"]))

df = pd.concat([df.reset_index(drop=True),geo_encoded_df],axis=1)
df.drop("Geography",axis=1,inplace=True)

c:\Users\HP\OneDrive\Documents\CustomerChurnPrediction\churnpred\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [74]:
sample_df = df.copy()

In [69]:
sample_df

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [75]:
sample_df_scaled = scaler.transform(sample_df)

In [82]:
sample_df_scaled

array([[-0.54204762,  0.91055421,  0.10473081, -0.68894811, -0.26230046,
         0.81966266,  0.64598061,  0.97071435, -0.88153859,  0.99828718,
        -0.57559072, -0.57779016]])

In [77]:
y_pred = model.predict(sample_df_scaled)

1/1 [==============================] - 0s 53ms/step


In [81]:
y_pred

array([[0.20054996]], dtype=float32)

In [79]:
prediction_probab = y_pred[0][0]

0.20054996